services:
  backend:
    build:
      dockerfile: ./backend/Dockerfile
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8080
      - PRIVACY_POLICY_URL=https://gist.github.com/sotterbeck/8dfdf24a2a4d6940a1d3af9cf479d7c1
