[versions]
kotlin-coroutines = "1.8.1"
kotlin-dataframe = "0.13.1"
assertk = "0.28.1"
mockk = "1.13.10"
apache-poi = "5.2.5"
skrapeit = "1.2.2"
okhttp = "4.12.0"
aedile = "1.3.1"
biweekly = "0.6.8"

[libraries]
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlin-coroutines" }
kotlin-dataframe = { module = "org.jetbrains.kotlinx:dataframe", version.ref = "kotlin-dataframe" }
apache-poi = { module = "org.apache.poi:poi", version.ref = "apache-poi" }
apache-poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "apache-poi" }
skrapeit = { module = "it.skrape:skrapeit", version.ref = "skrapeit" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
aedile = { module = "com.sksamuel.aedile:aedile-core", version.ref = "aedile" }
biweekly = { module = "net.sf.biweekly:biweekly", version.ref = "biweekly" }


assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertk" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }